### ISSUE TITLE
help with my code

### ISSUE THREAD

**Issue by projetoarduino** [isaacvitor/rf433pico#6]
Hello, I'm using your code but it doesn't deliver an address (id), so I started working on some modifications to a code that I already used in the arduino, with this something that looks like an address, but the Anti-Code that would be the 1010 at the end or beginning of the code is not valid and I can't extract the data or button1 and button2.

Would you help me ?

https://github.com/projetoarduino/rf433-ht6p20-micropython

**Comment by isaacvitor** [comment]
Sorry, but I can't help you.
